#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Cloud Functions Gen 1 -> Gen 2 cutover.
# Companion doc: docs/plans/gen2-functions-cutover.md
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=10

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Every function that carries no client coupling. These go first, as one batch:
# each tolerates a skipped cycle, so the gap costs nothing.
BACKGROUND_FNS=(
  cleanupStaleUsers
  cleanupInactiveAnonymousAccounts
  cleanupVideoCallSignaling
  onUserDisconnect
  validateUserPresence
  onPackReported
  manualCleanupStaleUsers
  manualCleanupAnonymousAccounts
)
# The client calls this one. It moves last and alone, to keep its gap shortest.
TURN_FN="getTurnCredentials"
REGION="us-central1"
STATE_DIR="${TMPDIR:-/tmp}/gen2-cutover"
mkdir -p "$STATE_DIR"

# only_list fn... -> "functions:a,functions:b" for a scoped firebase deploy.
# A bare `--only functions` would also try to redeploy the Gen 1 function still
# in place, which fails the same-name generation rule.
only_list() {
  local out="" fn
  for fn in "$@"; do out+="functions:${fn},"; done
  printf '%s' "${out%,}"
}

# gen_of fn -> GEN_1 | GEN_2 | (empty when the function does not exist)
gen_of() {
  # `|| true`: a gcloud/network failure must read as "unknown" rather than kill the
  # run under `set -e` — the caller already treats an empty answer as not-Gen-2.
  gcloud functions list --project "$PROJECT_ID" --filter="name:$1" \
    --format='value(environment)' 2>/dev/null | head -n1 || true
}

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }

banner "Cloud Functions Gen 1 -> Gen 2 cutover"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — tooling, auth, and the code you're about to ship"
say "Nothing is changed in this stage. We're only checking you can finish."
printf '\n'

command -v firebase >/dev/null 2>&1 || die "firebase CLI not found. brew install firebase-cli"
command -v gcloud   >/dev/null 2>&1 || die "gcloud not found — stages 8 and 9 need it. https://cloud.google.com/sdk/docs/install"
FIREBASE_VERSION="$(firebase --version 2>/dev/null | tail -n1)"
say "firebase-tools ${FIREBASE_VERSION}  $(printf '%s(Gen 2 has shipped since 11.x, so any current version is fine)%s' "$DIM" "$RESET")"
say "gcloud $(gcloud --version 2>/dev/null | head -n1 | awk '{print $NF}')"

if ! firebase login:list 2>/dev/null | grep -qi '@'; then
  warn "no logged-in firebase account detected."
  say "Run this in another terminal, then come back:  firebase login"
  pause "Press Enter once you're logged in."
fi

DEFAULT_PROJECT="$(python3 -c 'import json;print(json.load(open(".firebaserc"))["projects"]["default"])' 2>/dev/null || echo "")"
say ""
say "Project from .firebaserc: ${BOLD}${DEFAULT_PROJECT:-<none found>}${RESET}"
note "gcloud's own default project is ignored — every command below passes --project explicitly."
ask PROJECT_ID "Project id to deploy to [Enter for ${DEFAULT_PROJECT}]:"
[[ -z "$PROJECT_ID" ]] && PROJECT_ID="$DEFAULT_PROJECT"
[[ -n "$PROJECT_ID" ]] || die "no project id"
say ""

# gcloud's token expiring is the quiet one: firebase deploy would still work, and
# only stage 8 — the secret-access check, the whole point of verifying — would fail.
# So prove the credential against this project before changing anything.
GCLOUD_OK=0
for attempt in 1 2 3; do
  if gcloud functions list --project "$PROJECT_ID" --limit 1 >/dev/null 2>&1; then
    GCLOUD_OK=1; break
  fi
  warn "gcloud cannot read functions on ${PROJECT_ID} (attempt ${attempt}/3)."
  say "Most likely an expired token. In another terminal:"
  note "  gcloud auth login"
  note "  # and if that account isn't the right one:"
  note "  gcloud auth list"
  pause "Press Enter to retry."
done
if (( GCLOUD_OK )); then
  say "${GREEN}✓${RESET} gcloud can read functions on ${PROJECT_ID} as $(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | head -n1)"
else
  warn "continuing without working gcloud access."
  note "Stages 2, 6, 8, 9 and 10 are verification-only and will be blank —"
  note "which means you would be deploying with no way to confirm the result."
  confirm "Really continue blind?" || die "stopped — run 'gcloud auth login' and start again"
  SKIPPED+=("all gcloud verification: secret access, generation checks, scheduler orphans")
fi
say ""

BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
say "git branch: ${BRANCH}"
if git grep -q "firebase-functions/v1" -- functions/src 2>/dev/null; then
  die "functions/src still imports firebase-functions/v1 — you are not on the migrated code."
fi
say "${GREEN}✓${RESET} functions/src has no firebase-functions/v1 imports"
if ! git diff --quiet -- functions/ 2>/dev/null; then
  warn "functions/ has uncommitted changes — you'd be deploying something not in git."
  confirm "Continue anyway?" || die "stopped so you can commit first"
fi
pause "Preflight done. Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Snapshot — what is running right now"
say "Recording the current state so you can tell later what changed."
printf '\n'
if gcloud functions list --project "$PROJECT_ID" \
     --format='table(name,environment,state,updateTime)' >"$STATE_DIR/before.txt" 2>&1 \
   && grep -q GEN_ "$STATE_DIR/before.txt"; then
  cat "$STATE_DIR/before.txt"
  printf '\n'
  note "saved to $STATE_DIR/before.txt"
  say ""
  say "Expect all 9 to read ${BOLD}GEN_1${RESET}. If any already say GEN_2, that one is done —"
  say "skip it when we get there, because deleting it would be a step backwards."
else
  warn "couldn't list functions — no snapshot recorded."
  note "$(head -n3 "$STATE_DIR/before.txt" 2>/dev/null || true)"
  SKIPPED+=("record a before-snapshot of function generations")
fi
pause "Press Enter to continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Local gate — build and test before touching production"
say "The deploy runs its own build, but finding a failure here costs nothing."
printf '\n'
( cd functions && npm run type-check ) || die "functions type-check failed"
say "${GREEN}✓${RESET} type-check"
( cd functions && npm run build ) >/dev/null || die "functions build failed"
say "${GREEN}✓${RESET} build"
( cd functions && npm test ) || die "functions tests failed"
say "${GREEN}✓${RESET} tests"
pause "All green. Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Delete the 8 background + admin functions  [IRREVERSIBLE]"
say "A Gen 1 function cannot be replaced by a same-named Gen 2 one, so each has"
say "to be deleted first. This is the first change to production."
printf '\n'
for fn in "${BACKGROUND_FNS[@]}"; do step "$fn"; done
printf '\n'
say "While they're gone:"
note "  - the 4 scheduled cleanups skip cycles (harmless — they're idempotent sweeps)"
note "  - the 2 RTDB presence triggers don't fire (lastSeen backfill pauses)"
note "  - a pack reported in the gap sends no moderator email"
note "  - the 2 admin callables 404 (nothing in the app calls them)"
printf '\n'
confirm "Delete these 8 from ${PROJECT_ID}?" || die "stopped before any change"
firebase functions:delete "${BACKGROUND_FNS[@]}" --project "$PROJECT_ID" --region "$REGION" --force \
  || warn "delete reported an error — read it above; already-absent functions are fine"
pause "Press Enter to deploy them back as Gen 2."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Deploy the 8 as Gen 2"
say "Scoped deploy — a bare '--only functions' would also try to redeploy the"
say "Gen 1 ${TURN_FN} that's still in place, and fail on it."
printf '\n'
firebase deploy --only "$(only_list "${BACKGROUND_FNS[@]}")" --project "$PROJECT_ID" \
  || die "deploy failed — the 8 are currently absent. Fix the error and re-run this stage."
pause "Press Enter to verify."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify the 8"
printf '\n'
FAILED=()
for fn in "${BACKGROUND_FNS[@]}"; do
  g="$(gen_of "$fn")"
  case "$g" in
    GEN_2) printf '  %s✓%s %-34s %s\n' "$GREEN" "$RESET" "$fn" "$g" ;;
    "")    printf '  %s✗%s %-34s %s\n' "$RED" "$RESET" "$fn" "MISSING"; FAILED+=("$fn") ;;
    *)     printf '  %s✗%s %-34s %s\n' "$RED" "$RESET" "$fn" "$g"; FAILED+=("$fn") ;;
  esac
done
printf '\n'
if (( ${#FAILED[@]} )); then
  warn "not Gen 2 yet: ${FAILED[*]}"
  confirm "Continue to the TURN function anyway?" || die "stopped — re-run stage 5 first"
else
  say "${GREEN}All 8 are Gen 2.${RESET}"
fi
pause "Press Enter."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "$TURN_FN — delete and redeploy  [IRREVERSIBLE]"
say "This is the one the app calls. Same name, so same delete-first rule."
printf '\n'
say "During the gap, resolveIceServers (src/services/iceServers.ts) catches the"
say "error and falls back to the bundled relay — calls keep working on lower-"
say "quality relay rather than failing. Nothing to change client-side."
printf '\n'
warn "If the deploy fails after the delete, TURN stays down until you fix it."
printf '\n'
confirm "Delete and redeploy ${TURN_FN}?" || die "stopped — the other 8 are already Gen 2, which is a fine place to pause"
firebase functions:delete "$TURN_FN" --project "$PROJECT_ID" --region "$REGION" --force \
  || warn "delete reported an error — read it above"
firebase deploy --only "$(only_list "$TURN_FN")" --project "$PROJECT_ID" \
  || die "TURN deploy failed and ${TURN_FN} is now absent. Re-run: firebase deploy --only functions:${TURN_FN} --project ${PROJECT_ID}"
printf '\n'
say "$TURN_FN is now: ${BOLD}$(gen_of "$TURN_FN")${RESET}"
pause "Press Enter."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Secret access — the failure that makes no noise"
say "Gen 2 runs as a different default service account than Gen 1's"
say "<project>@appspot.gserviceaccount.com. If the Secret Manager grants didn't"
say "follow it, both failures are silent degradations:"
printf '\n'
note "  - no CLOUDFLARE_TURN_TOKEN -> failed-precondition -> client quietly uses the bundled relay"
note "  - no SENDGRID_API_KEY      -> logged error, returns -> pack reports quietly stop emailing"
printf '\n'
SA="$(gcloud functions describe "$TURN_FN" --gen2 --region "$REGION" --project "$PROJECT_ID" \
       --format='value(serviceConfig.serviceAccountEmail)' 2>/dev/null || true)"
if [[ -z "$SA" ]]; then
  warn "couldn't read the service account — check by hand:"
  note "  gcloud functions describe $TURN_FN --gen2 --region $REGION --project $PROJECT_ID"
  SKIPPED+=("verify Secret Manager access for CLOUDFLARE_TURN_TOKEN and SENDGRID_API_KEY")
else
  say "Gen 2 service account: ${BOLD}${SA}${RESET}"
  printf '\n'
  for secret in CLOUDFLARE_TURN_TOKEN SENDGRID_API_KEY; do
    if gcloud secrets get-iam-policy "$secret" --project "$PROJECT_ID" 2>/dev/null | grep -q "$SA"; then
      printf '  %s✓%s %-24s %s has access\n' "$GREEN" "$RESET" "$secret" "$SA"
    else
      printf '  %s✗%s %-24s no binding for %s\n' "$RED" "$RESET" "$secret" "$SA"
      if confirm "Grant secretAccessor on ${secret} to ${SA}?"; then
        if gcloud secrets add-iam-policy-binding "$secret" \
             --member="serviceAccount:${SA}" \
             --role=roles/secretmanager.secretAccessor \
             --project "$PROJECT_ID" >/dev/null; then
          say "  ${GREEN}✓${RESET} granted"
        else
          warn "grant failed — do it in the console"
          SKIPPED+=("grant secretAccessor on $secret to $SA")
        fi
      else
        SKIPPED+=("grant secretAccessor on $secret to $SA")
      fi
    fi
  done
fi
pause "Press Enter."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Scheduler jobs — check for orphans"
say "The deleted Gen 1 schedules may leave Cloud Scheduler jobs behind. Harmless"
say "(they fire at nothing) but they clutter the console and the logs."
printf '\n'
gcloud scheduler jobs list --project "$PROJECT_ID" \
  --format='table(name,schedule,state)' 2>&1 | tee "$STATE_DIR/scheduler.txt" || \
  warn "couldn't list scheduler jobs — check the console"
printf '\n'
say "Expect one job per scheduled function. A duplicate pair for the same function"
say "means the Gen 1 job is an orphan; delete it with:"
note "  gcloud scheduler jobs delete <JOB_NAME> --project $PROJECT_ID"
pause "Press Enter."

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Final check"
printf '\n'
gcloud functions list --project "$PROJECT_ID" \
  --format='table(name,environment,state)' 2>&1 | tee "$STATE_DIR/after.txt" || true
printf '\n'
say "Every row should read ${BOLD}GEN_2${RESET}. Before/after tables are in $STATE_DIR."
printf '\n'
say "${BOLD}One thing only a human can check:${RESET}"
step "Open the app, join a room, turn the webcam on."
step "Confirm the browser gets Cloudflare ICE servers, not the bundled VITE_METERED_* ones."
note "  A silent fall back to the bundled relay is exactly what a missing secret looks like."
printf '\n'
say "${BOLD}Now unlocked:${RESET} nodejs24 is 2nd-gen only, so functions/package.json can"
say "move engines.node 22 -> 24 — but that needs firebase-tools 15.x (you have"
say "${FIREBASE_VERSION}). Node 22 is supported until 2027-04-30, so it can wait."
pause "Press Enter to finish."

finish
